// equipment.js

export const WEAPONS = {
    // --- 神器 (8) ---
    godSlayer: { id: 'godSlayer', name: '弒神者', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 200, def: 50, hit: 30 }, description: '傳說中曾斬落神明的禁忌之劍。特殊效果：對首領級敵人傷害增加25%。', value: 99999, rarity: 'legendary' },
    fistOfEnlightenment: { id: 'fistOfEnlightenment', name: '悟道之拳', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { atk: 80, spi: 180, mp: 100 }, description: '蘊含宇宙真理的拳套。特殊效果：技能消耗的法力減少30%。', value: 99999, rarity: 'legendary' },
    worldEnder: { id: 'worldEnder', name: '滅世者', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 250, hp: 300, speed: -10 }, description: '足以粉碎大地的巨斧。特殊效果：攻擊有機率造成範圍傷害。', value: 99999, rarity: 'legendary' },
    soulReaperScythe: { id: 'soulReaperScythe', name: '收魂者之鐮', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 220, eva: 20 }, description: '收割靈魂的巨大鐮刀。特殊效果：擊敗敵人時恢復20%最大生命值。', value: 99999, rarity: 'legendary' },
    aegisBlade: { id: 'aegisBlade', name: '聖盾埃癸斯', type: 'weapon', slot: 'weapon', class: ['swordsman', 'monk'], stats: { atk: 150, def: 80, spi: 80 }, description: '由女神雅典娜祝福的劍盾合體兵器，擁有絕對的守護之力。', value: 120000, rarity: 'legendary' },
    voidcallerStaff: { id: 'voidcallerStaff', name: '虛空呼喚者', type: 'weapon', slot: 'weapon', class: ['monk', 'necromancer'], stats: { spi: 250, mp: 200, hit: 20 }, description: '能夠撕裂現實，從虛空中汲取混沌能量的法杖。', value: 120000, rarity: 'legendary' },
    gigasSmasher: { id: 'gigasSmasher', name: '巨靈碎擊者', type: 'weapon', slot: 'weapon', class: ['swordsman', 'orc'], stats: { atk: 280, hp: 400, critDamage: 50 }, description: '傳說泰坦用來塑造山脈的巨錘，每一擊都帶有開天闢地的力量。', value: 120000, rarity: 'legendary' },
    bloodthornAxe: { id: 'bloodthornAxe', name: '血棘', type: 'weapon', slot: 'weapon', class: ['orc', 'necromancer'], stats: { atk: 220, spi: 150, eva: -15 }, description: '由惡魔心臟與荊棘木融合而成的活體戰斧，渴望著鮮血與靈魂。', value: 120000, rarity: 'legendary' },

    // --- 劍客武器 (10) ---
    smallSword: { id: 'smallSword', name: '小劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 3, hit: 2 }, description: '一把普通的單手劍。', value: 20, rarity: 'common' },
    fineLongsword: { id: 'fineLongsword', name: '精良長劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 8, hit: 4 }, description: '由軍團工匠打造的長劍。', value: 120, rarity: 'uncommon' },
    knightSword: { id: 'knightSword', name: '騎士劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 14, def: 3, hit: 5 }, description: '騎士的標準配劍。', value: 320, rarity: 'uncommon' },
    greatsword: { id: 'greatsword', name: '巨劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 22, speed: -2 }, description: '沉重但威力巨大。', value: 600, rarity: 'rare' },
    runeBlade: { id: 'runeBlade', name: '符文之刃', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 28, spi: 10, hit: 8 }, description: '刻有增強力量符文的魔法劍。', value: 1100, rarity: 'rare' },
    crystalSword: { id: 'crystalSword', name: '水晶劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 35, critRate: 5 }, description: '由純淨的魔法水晶製成。', value: 2500, rarity: 'epic' },
    flameberd: { id: 'flameberd', name: '焰形劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 45, spi: 15 }, description: '劍刃如同燃燒的火焰。', value: 5000, rarity: 'epic' },
    dragonSlayer: { id: 'dragonSlayer', name: '屠龍者', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 60, def: 15 }, description: '為對抗巨龍而打造的傳說武器。', value: 12000, rarity: 'epic' },
    vorpalSword: { id: 'vorpalSword', name: '瞬殺劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 75, speed: 10, critRate: 10 }, description: '能夠斬斷時空的利刃，快得讓人無法反應。', value: 20000, rarity: 'epic' },
    excalibur: { id: 'excalibur', name: '王者之劍', type: 'weapon', slot: 'weapon', class: ['swordsman'], stats: { atk: 90, def: 25, hit: 15 }, description: '唯有被選中的王者才能拔出的聖劍，象徵著榮耀與勝利。', value: 35000, rarity: 'epic' },

    // --- 修士武器 (10) ---
    monksGloves: { id: 'monksGloves', name: '修行者拳套', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { atk: 2, spi: 4, hit: 3 }, description: '纏繞著信念的布手套。', value: 25, rarity: 'common' },
    acolyteBeads: { id: 'acolyteBeads', name: '見習修士念珠', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 8, mp: 15, hit: 5 }, description: '注入了禱文的木製念珠。', value: 120, rarity: 'uncommon' },
    ironFist: { id: 'ironFist', name: '鐵拳', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { atk: 10, spi: 8, def: 5 }, description: '鑲嵌鐵片的重型拳套。', value: 320, rarity: 'uncommon' },
    spiritChakram: { id: 'spiritChakram', name: '靈氣環刃', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 20, speed: 5 }, description: '由純粹能量構成的環刃。', value: 600, rarity: 'rare' },
    wisdomStaff: { id: 'wisdomStaff', name: '智慧法杖', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 25, mp: 50 }, description: '鑲嵌著智慧寶石的法杖。', value: 1100, rarity: 'rare' },
    glovesOfSerenity: { id: 'glovesOfSerenity', name: '寧靜之拳', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 32, eva: 8 }, description: '能讓佩戴者心如止水。', value: 2500, rarity: 'epic' },
    staffOfBalance: { id: 'staffOfBalance', name: '平衡法杖', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 40, def: 10, mp: 30 }, description: '維持生死平衡的聖物。', value: 5000, rarity: 'epic' },
    dragonClaw: { id: 'dragonClaw', name: '龍爪', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { atk: 30, spi: 35, critRate: 5 }, description: '模仿龍爪製成的致命武器。', value: 12000, rarity: 'epic' },
    vajra: { id: 'vajra', name: '金剛杵', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { atk: 40, spi: 55, def: 15 }, description: '無堅不摧的降魔聖器，能破除一切邪惡。', value: 20000, rarity: 'epic' },
    scepterOfSamsara: { id: 'scepterOfSamsara', name: '輪迴權杖', type: 'weapon', slot: 'weapon', class: ['monk'], stats: { spi: 80, mp: 120 }, description: '掌控著生命輪迴的權杖，蘊含著創生與寂滅的力量。', value: 35000, rarity: 'epic' },

    // --- 獸人武器 (10) ---
    orcishAxe: { id: 'orcishAxe', name: '獸人手斧', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 5, hit: 1 }, description: '粗製但致命的武器。', value: 30, rarity: 'common' },
    boneCrusher: { id: 'boneCrusher', name: '碎骨棒', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 12, hp: 20 }, description: '沾滿不知名生物體液的巨大棍棒。', value: 120, rarity: 'uncommon' },
    spikedClub: { id: 'spikedClub', name: '狼牙棒', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 18, critDamage: 10 }, description: '佈滿尖刺的殘忍武器。', value: 320, rarity: 'uncommon' },
    greatAxe: { id: 'greatAxe', name: '巨斧', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 28 }, description: '只有獸人才能揮舞的巨大戰斧。', value: 600, rarity: 'rare' },
    trollHammer: { id: 'trollHammer', name: '巨魔戰錘', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 35, hp: 50 }, description: '用來粉碎巨魔頭骨的錘子。', value: 1100, rarity: 'rare' },
    berserkerAxe: { id: 'berserkerAxe', name: '狂戰士之斧', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 45, critRate: 8, def: -10 }, description: '讓使用者陷入瘋狂，只攻不守。', value: 2500, rarity: 'epic' },
    ogreMaul: { id: 'ogreMaul', name: '食人魔大槌', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 55 }, description: '據說是用食人魔的腿骨製成。', value: 5000, rarity: 'epic' },
    dragonToothAxe: { id: 'dragonToothAxe', name: '龍牙巨斧', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 70, critDamage: 20 }, description: '嵌入了龍牙的傳說級武器。', value: 12000, rarity: 'epic' },
    chieftainsCleaver: { id: 'chieftainsCleaver', name: '督軍斬首斧', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 85, hp: 100 }, description: '部落督軍的權力象徵，曾斬下無數敵人的首級。', value: 20000, rarity: 'epic' },
    earthshaker: { id: 'earthshaker', name: '撼地者', type: 'weapon', slot: 'weapon', class: ['orc'], stats: { atk: 100, def: 20, speed: -5 }, description: '傳說每一次揮舞都能引發地震的恐怖武器。', value: 35000, rarity: 'epic' },

    // --- 死靈武器 (10) ---
    boneWand: { id: 'boneWand', name: '骸骨魔棒', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 6, hit: 4 }, description: '散發著微弱的靈魂能量。', value: 40, rarity: 'common' },
    specterWand: { id: 'specterWand', name: '怨靈法杖', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 10, mp: 20, hit: 7 }, description: '頂端的水晶封印著一個不安的靈魂。', value: 120, rarity: 'uncommon' },
    ritualDagger: { id: 'ritualDagger', name: '儀式匕首', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { atk: 8, spi: 10 }, description: '用於黑暗儀式的匕首。', value: 320, rarity: 'uncommon' },
    staffOfCurse: { id: 'staffOfCurse', name: '詛咒法杖', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 22 }, description: '能放大詛咒效果的法杖。', value: 600, rarity: 'rare' },
    lichSpine: { id: 'lichSpine', name: '巫妖脊骨', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 28, mp: 40 }, description: '一根強大巫妖的脊骨，仍充滿魔力。', value: 1100, rarity: 'rare' },
    wandOfPain: { id: 'wandOfPain', name: '痛苦魔棒', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 38 }, description: '每一次揮舞都帶來痛苦與哀嚎。', value: 2500, rarity: 'epic' },
    soulSiphon: { id: 'soulSiphon', name: '靈魂虹吸', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 42, mp: 80 }, description: '能吸取敵人靈魂能量的法器。', value: 5000, rarity: 'epic' },
    staffOfApocalypse: { id: 'staffOfApocalypse', name: '天啟法杖', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 65, eva: 10 }, description: '據說能引發末日，帶來死亡與毀滅。', value: 12000, rarity: 'epic' },
    netherTome: { id: 'netherTome', name: '冥界魔典', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 80, eva: 15 }, description: '記載著禁忌知識與靈魂契約的書本，能扭曲生死法則。', value: 20000, rarity: 'epic' },
    hadesGrasp: { id: 'hadesGrasp', name: '冥王之握', type: 'weapon', slot: 'weapon', class: ['necromancer'], stats: { spi: 95, hp: 150 }, description: '彷彿由冥界本身伸出的手骨製成的法器，緊握著死亡的權柄。', value: 35000, rarity: 'epic' },
};

export const EQUIPMENT = {
    // --- 護甲 (21) ---
    leatherArmor: { id: 'leatherArmor', name: '皮甲', type: 'armor', slot: 'armor', stats: { def: 5, eva: 2 }, description: '基本的皮革護甲。', value: 25, rarity: 'common' },
    chainmail: { id: 'chainmail', name: '鎖子甲', type: 'armor', slot: 'armor', stats: { def: 12 }, description: '能有效抵禦劈砍的金屬甲。', value: 100, rarity: 'uncommon' },
    mageRobe: { id: 'mageRobe', name: '法師長袍', type: 'armor', slot: 'armor', stats: { def: 3, spi: 8 }, description: '繡有符文的布袍。', value: 70, rarity: 'uncommon' },
    plateArmor: { id: 'plateArmor', name: '板甲', type: 'armor', slot: 'armor', stats: { def: 20, speed: -5 }, description: '提供絕佳防護的重型盔甲。', value: 300, rarity: 'rare' },
    shadowCloak: { id: 'shadowCloak', name: '暗影斗篷', type: 'armor', slot: 'armor', stats: { def: 8, eva: 10 }, description: '能融入陰影的魔法斗篷。', value: 450, rarity: 'epic'},
    dragonScaleMail: { id: 'dragonScaleMail', name: '龍鱗甲', type: 'armor', slot: 'armor', stats: { def: 35, spi: 15 }, description: '由巨龍鱗片製成的傳說護甲。', value: 15000, rarity: 'legendary' },
    studdedLeather: { id: 'studdedLeather', name: '鑲釘皮甲', type: 'armor', slot: 'armor', stats: { def: 8, eva: 4 }, description: '在關鍵部位加強了金屬鉚釘的皮甲。', value: 150, rarity: 'uncommon' },
    scholarRobe: { id: 'scholarRobe', name: '學者長袍', type: 'armor', slot: 'armor', stats: { def: 4, mp: 30 }, description: '便於冥想和施法的寬鬆長袍。', value: 130, rarity: 'uncommon' },
    barbarianHarness: { id: 'barbarianHarness', name: '野蠻人護具', type: 'armor', slot: 'armor', stats: { def: 10, hp: 25 }, description: '由獸皮與骨片製成的輕便護甲。', value: 180, rarity: 'uncommon' },
    knightsPlate: { id: 'knightsPlate', name: '騎士板甲', type: 'armor', slot: 'armor', stats: { def: 25, hp: 50, speed: -6 }, description: '皇家騎士團的制式重甲。', value: 800, rarity: 'rare' },
    elvenChainmail: { id: 'elvenChainmail', name: '精靈鎖子甲', type: 'armor', slot: 'armor', stats: { def: 18, eva: 8 }, description: '由精靈工匠打造，輕盈而堅韌。', value: 1200, rarity: 'rare' },
    archmageRobes: { id: 'archmageRobes', name: '大法師之袍', type: 'armor', slot: 'armor', stats: { def: 12, spi: 25, mp: 80 }, description: '蘊含強大魔力的長袍，能增幅施法者的力量。', value: 3000, rarity: 'rare' },
    assassinsGarb: { id: 'assassinsGarb', name: '刺客信條', type: 'armor', slot: 'armor', stats: { def: 15, eva: 15, critRate: 5 }, description: '專為潛行與暗殺設計的服裝。', value: 4500, rarity: 'epic' },
    demonhideArmor: { id: 'demonhideArmor', name: '惡魔皮甲', type: 'armor', slot: 'armor', stats: { def: 28, spi: 20 }, description: '剝取自深淵惡魔的皮膚製成，帶有不祥的氣息。', value: 6000, rarity: 'epic' },
    adamantitePlate: { id: 'adamantitePlate', name: '精金板甲', type: 'armor', slot: 'armor', stats: { def: 40, speed: -8 }, description: '由最堅硬的金屬「精金」打造，幾乎無法被摧毀。', value: 8000, rarity: 'epic' },
    robeOfSeraph: { id: 'robeOfSeraph', name: '熾天使之袍', type: 'armor', slot: 'armor', stats: { def: 20, spi: 40, hp: 100 }, description: '據說由天使的羽翼織成，散發著神聖的光芒。', value: 10000, rarity: 'epic' },
    behemothHide: { id: 'behemothHide', name: '巨獸皮鎧', type: 'armor', slot: 'armor', stats: { def: 38, hp: 200 }, description: '使用傳說巨獸貝西摩斯的硬皮製成。', value: 9000, rarity: 'epic' },
    voidmantle: { id: 'voidmantle', name: '虛空罩篷', type: 'armor', slot: 'armor', stats: { def: 22, eva: 20, spi: 18 }, description: '彷彿由純粹的黑暗構成，能夠扭曲光線。', value: 7500, rarity: 'epic' },
    celestialArmor: { id: 'celestialArmor', name: '天界戰甲', type: 'armor', slot: 'armor', stats: { def: 50, hp: 150, spi: 25 }, description: '神域工匠為天界戰士打造的護甲。', value: 25000, rarity: 'legendary' },
    abyssalMail: { id: 'abyssalMail', name: '深淵鍊甲', type: 'armor', slot: 'armor', stats: { def: 45, atk: 20 }, description: '在混沌的深淵中鍛造，會腐蝕敵人的靈魂。', value: 22000, rarity: 'legendary' },

    // --- 配件 (17) ---
    courageBadge: { id: 'courageBadge', name: '勇氣徽章', type: 'accessory', slot: 'accessory', stats: { atk: 3 }, description: '一枚小小的徽章，能激發潛力。', value: 50, rarity: 'common' },
    guardianRing: { id: 'guardianRing', name: '守護者之戒', type: 'accessory', slot: 'accessory', stats: { def: 3 }, description: '鑲嵌著守護石的戒指。', value: 50, rarity: 'common' },
    amuletOfPower: { id: 'amuletOfPower', name: '力量護符', type: 'accessory', slot: 'accessory', stats: { atk: 8, spi: 8 }, description: '同時增強物理與魔法力量。', value: 500, rarity: 'rare' },
    ringOfVitality: { id: 'ringOfVitality', name: '活力戒指', type: 'accessory', slot: 'accessory', stats: { hp: 100 }, description: '大幅增加配戴者的生命力。', value: 1200, rarity: 'epic' },
    manaStone: { id: 'manaStone', name: '法力石', type: 'accessory', slot: 'accessory', stats: { mp: 25 }, description: '一塊充滿魔力的石頭，能增加法力儲備。', value: 60, rarity: 'common' },
    luckyCharm: { id: 'luckyCharm', name: '幸運符', type: 'accessory', slot: 'accessory', stats: { critRate: 2 }, description: '據說能帶來好運的護身符。', value: 150, rarity: 'uncommon' },
    ringOfPrecision: { id: 'ringOfPrecision', name: '精準之戒', type: 'accessory', slot: 'accessory', stats: { hit: 10 }, description: '能讓攻擊更加準確。', value: 300, rarity: 'uncommon' },
    berserkersEmblem: { id: 'berserkersEmblem', name: '狂戰士紋章', type: 'accessory', slot: 'accessory', stats: { atk: 12, def: -5 }, description: '犧牲防禦以換取更強大的攻擊力。', value: 600, rarity: 'rare' },
    sagesAmulet: { id: 'sagesAmulet', name: '賢者護符', type: 'accessory', slot: 'accessory', stats: { spi: 15, mp: 50 }, description: '古代賢者佩戴的護符，充滿智慧的能量。', value: 800, rarity: 'rare' },
    philosophersStone: { id: 'philosophersStone', name: '賢者之石', type: 'accessory', slot: 'accessory', stats: { hp: 50, mp: 50 }, description: '鍊金術的極致產物，蘊含著生命的奧秘。', value: 1000, rarity: 'rare' },
    // [新增] 補齊50件裝備
    thiefsRune: { id: 'thiefsRune', name: '盜賊的符文', type: 'accessory', slot: 'accessory', stats: { speed: 8, eva: 5 }, description: '刻有風之符文的石片，能讓腳步更輕盈。', value: 750, rarity: 'rare' },
    medallionOfEndurance: { id: 'medallionOfEndurance', name: '耐力獎章', type: 'accessory', slot: 'accessory', stats: { hp: 80, def: 5 }, description: '增強佩戴者的耐力與體格。', value: 900, rarity: 'rare' },
    titansBelt: { id: 'titansBelt', name: '泰坦腰帶', type: 'accessory', slot: 'accessory', stats: { hp: 250 }, description: '傳說中泰坦巨人使用的腰帶，蘊含龐大的生命力。', value: 3000, rarity: 'epic' },
    archonsSignet: { id: 'archonsSignet', name: '執政官印戒', type: 'accessory', slot: 'accessory', stats: { atk: 15, spi: 15, def: 10 }, description: '古代統治者的戒指，全面提升佩戴者的能力。', value: 5000, rarity: 'epic' },
    eyeOfTheStorm: { id: 'eyeOfTheStorm', name: '風暴之眼', type: 'accessory', slot: 'accessory', stats: { speed: 20, eva: 10 }, description: '一顆封印了風暴核心的寶石。', value: 4500, rarity: 'epic' },
    bloodstone: { id: 'bloodstone', name: '血石', type: 'accessory', slot: 'accessory', stats: { hp: 120, atk: 10 }, description: '吸收戰場上的鮮血而變紅的魔石。', value: 3500, rarity: 'epic' },
    soulCage: { id: 'soulCage', name: '靈魂囚籠', type: 'accessory', slot: 'accessory', stats: { mp: 150, spi: 20 }, description: '一個用來囚禁弱小靈魂的護符，可以作為法力源泉。', value: 4000, rarity: 'epic' },
    heartOfTarrasque: { id: 'heartOfTarrasque', name: '魔龍之心', type: 'accessory', slot: 'accessory', stats: { hp: 500, def: 20 }, description: '傳說中的不朽魔物之心，提供無盡的生命力。', value: 18000, rarity: 'legendary' },
    
    // --- 靴子 (13) ---
    travelersBoots: { id: 'travelersBoots', name: '旅者之靴', type: 'boots', slot: 'boots', stats: { speed: 5, eva: 2 }, description: '適合長途旅行的靴子。', value: 80, rarity: 'common' },
    steelGreaves: { id: 'steelGreaves', name: '鋼鐵護脛', type: 'boots', slot: 'boots', stats: { def: 8, speed: -2 }, description: '沉重的鋼鐵靴子。', value: 400, rarity: 'uncommon' },
    bootsOfSwiftness: { id: 'bootsOfSwiftness', name: '迅捷之靴', type: 'boots', slot: 'boots', stats: { speed: 15, eva: 5 }, description: '讓穿戴者身輕如燕。', value: 1500, rarity: 'rare' },
    sandals: { id: 'sandals', name: '草鞋', type: 'boots', slot: 'boots', stats: { speed: 2 }, description: '用稻草編織的簡易鞋子。', value: 15, rarity: 'common' },
    guardsBoots: { id: 'guardsBoots', name: '衛兵之靴', type: 'boots', slot: 'boots', stats: { def: 4 }, description: '城鎮衛兵的標準配備。', value: 120, rarity: 'uncommon' },
    silentStriders: { id: 'silentStriders', name: '無聲之靴', type: 'boots', slot: 'boots', stats: { eva: 8 }, description: '可以消除腳步聲的魔法靴子。', value: 600, rarity: 'rare' },
    platedGreaves: { id: 'platedGreaves', name: '板甲護脛', type: 'boots', slot: 'boots', stats: { def: 12, speed: -4 }, description: '與板甲配套的重型靴子，防護力十足。', value: 900, rarity: 'rare' },
    windDancers: { id: 'windDancers', name: '風舞者之靴', type: 'boots', slot: 'boots', stats: { speed: 20, eva: 10 }, description: '穿上它就像與風共舞。', value: 3500, rarity: 'epic' },
    golemsStompers: { id: 'golemsStompers', name: '魔像踐踏者', type: 'boots', slot: 'boots', stats: { def: 18, atk: 5 }, description: '由石巨人的核心製成，每一步都沉重無比。', value: 4000, rarity: 'epic' },
    bootsOfTeleportation: { id: 'bootsOfTeleportation', name: '相位之靴', type: 'boots', slot: 'boots', stats: { speed: 25 }, description: '能夠進行短距離空間跳躍的神奇靴子。', value: 7000, rarity: 'epic' },
    dragonridersGreaves: { id: 'dragonridersGreaves', name: '龍騎士護脛', type: 'boots', slot: 'boots', stats: { def: 15, spi: 10, speed: 10 }, description: '傳說龍騎士的裝備，能抵禦龍息。', value: 6500, rarity: 'epic' },
    hermesSandals: { id: 'hermesSandals', name: '神速之靴', type: 'boots', slot: 'boots', stats: { speed: 40, eva: 15 }, description: '傳令之神赫爾墨斯的靴子，賜予穿戴者無與倫比的速度。', value: 20000, rarity: 'legendary' },
};