export const skills = {
    // --- 劍客 (Swordsman) ---
    slash: { name: '斬擊', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 1, 
        levels: [
            { mpCost: 5, damageMultiplier: 1.5, description: '[單體] 對單一敵人造成<span class="text-yellow-400">150%</span>攻擊力的物理傷害。' },
            { mpCost: 6, damageMultiplier: 1.65, description: '[單體] 對單一敵人造成<span class="text-yellow-400">165%</span>攻擊力的物理傷害。' },
            { mpCost: 7, damageMultiplier: 1.7, effect: { id: 'slash-buff', name: '斬擊強化', type: 'buff', stat: 'atk', value: 15, turns: 2 }, description: '[單體] 造成<span class="text-yellow-400">170%</span>物理傷害，並提升自身<span class="text-green-400">15</span>點攻擊力，持續2回合。' },
    ]},
    whirlwind: { name: '旋風斬', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'all', maxLevel: 3, levelReq: 3, prerequisite: { skillId: 'slash', level: 2 }, 
        levels: [
            { mpCost: 15, damageMultiplier: 1.2, description: '[範圍] 對所有敵人造成<span class="text-yellow-400">120%</span>攻擊力的物理傷害。' },
            { mpCost: 17, damageMultiplier: 1.3, description: '[範圍] 對所有敵人造成<span class="text-yellow-400">130%</span>攻擊力的物理傷害。' },
            { mpCost: 19, damageMultiplier: 1.4, effect: { id: 'whirlwind-buff', name: '加速', type: 'buff', stat: 'speed', value: 5, turns: 2 }, description: '[範圍] 造成<span class="text-yellow-400">140%</span>物理傷害，並提升自身<span class="text-green-400">5</span>點速度，持續2回合。' },
    ]},
    powerStrike: { name: '強力打擊', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 5, prerequisite: { skillId: 'slash', level: 3 }, 
        levels: [
            { mpCost: 10, damageMultiplier: 1.8, description: '[單體] 蓄力一擊，造成<span class="text-yellow-400">180%</span>攻擊力的巨大傷害。' },
            { mpCost: 12, damageMultiplier: 1.9, description: '[單體] 蓄力一擊，造成<span class="text-yellow-400">190%</span>攻擊力的巨大傷害。' },
            { mpCost: 14, damageMultiplier: 2.0, special: { type: 'double_damage_chance', chance: 0.25 }, description: '[單體] 造成<span class="text-yellow-400">200%</span>物理傷害，且有<span class="text-red-400">25%</span>機率造成2倍傷害。' },
    ]},
    shieldBash: { name: '盾牌猛擊', class:'swordsman', category: '控制', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 8, prerequisite: { skillId: 'whirlwind', level: 1 }, 
        levels: [
            { mpCost: 12, damageMultiplier: 1.2, effect: { id: 'stun', name: '昏迷', type: 'stun', turns: 1 }, description: '[單體] 造成<span class="text-yellow-400">120%</span>物理傷害，並使其<span class="text-orange-400">昏迷</span>一回合。' },
            { mpCost: 14, damageMultiplier: 1.3, effect: { id: 'stun', name: '昏迷', type: 'stun', turns: 1 }, description: '[單體] 造成<span class="text-yellow-400">130%</span>物理傷害，並使其<span class="text-orange-400">昏迷</span>一回合。' },
            { mpCost: 16, damageMultiplier: 1.4, effect: { id: 'stun', name: '昏迷', type: 'stun', turns: 1 }, description: '[單體] 造成<span class="text-yellow-400">140%</span>物理傷害，並使其<span class="text-orange-400">昏迷</span>一回合。' },
    ]},
    charge: { name: '衝鋒', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 12, prerequisite: { skillId: 'powerStrike', level: 2 }, 
        levels: [
            { mpCost: 15, damageMultiplier: 1.7, special: { type: 'delay_turn' }, description: '[單體] 造成<span class="text-yellow-400">170%</span>物理傷害，並<span class="text-orange-400">延後其行動</span>。' },
            { mpCost: 16, damageMultiplier: 1.77, special: { type: 'delay_turn' }, description: '[單體] 造成<span class="text-yellow-400">177%</span>物理傷害，並<span class="text-orange-400">延後其行動</span>。' },
            { mpCost: 17, damageMultiplier: 1.82, special: { type: 'delay_turn' }, description: '[單體] 造成<span class="text-yellow-400">182%</span>物理傷害，並<span class="text-orange-400">延後其行動</span>。' },
    ]},
    defensiveStance: { name: '防禦姿態', class:'swordsman', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 6, 
        levels: [
            { mpCost: 10, effect: { id: 'defensiveStance', name: '防禦姿態', type: 'buff', stat: 'def', value: 20, turns: 3}, description: '[增益] 提升<span class="text-green-400">20</span>點防禦力，持續3回合。' },
            { mpCost: 12, effect: { id: 'defensiveStance', name: '防禦姿態', type: 'buff', stat: 'def', value: 25, turns: 3}, description: '[增益] 提升<span class="text-green-400">25</span>點防禦力，持續3回合。' },
            { mpCost: 14, effect: { id: 'defensiveStance', name: '防禦姿態', type: 'buff', stat: 'def', value: 30, turns: 3}, description: '[增益] 提升<span class="text-green-400">30</span>點防禦力，持續3回合。' },
    ]},
    battleStance: { name: '戰鬥姿態', class:'swordsman', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 10, prerequisite: { skillId: 'defensiveStance', level: 1 },
        levels: [
            { mpCost: 18, effect: { id: 'battleStance', name: '戰鬥姿態', type: 'buff', stat: 'atk', value: 10, turns: 3}, description: '[增益] 提升<span class="text-green-400">10</span>點攻擊力，持續3回合。' },
            { mpCost: 20, effect: { id: 'battleStance', name: '戰鬥姿態', type: 'buff', stat: 'atk', value: 15, turns: 3}, description: '[增益] 提升<span class="text-green-400">15</span>點攻擊力，持續3回合。' },
            { mpCost: 22, effect: { id: 'battleStance', name: '戰鬥姿態', type: 'buff', stat: 'atk', value: 25, turns: 3}, description: '[增益] 提升<span class="text-green-400">25</span>點攻擊力，持續3回合。' },
    ]},
    ironWill: { name: '鋼鐵意志', class:'swordsman', category: '被動', type: 'passive', maxLevel: 1, levelReq: 15,
        levels: [{ description: '[被動] 生命低於30%時，防禦力提升<span class="text-green-400">40</span>，持續2回合(每場戰鬥觸發一次)。'}] },
    lastStand: { name: '背水一戰', class:'swordsman', category: '輔助', type: 'utility', targetType: 'self', maxLevel: 1, levelReq: 20, prerequisite: { skillId: 'ironWill', level: 1 }, 
        levels: [{ special: { type: 'last_stand' }, description: '[輔助] 消耗<span class="text-blue-400">2/3</span>最大法力，下一次攻擊必定<span class="text-red-500">暴擊</span>。'}] },
    bladeStorm: { name: '劍刃風暴', class:'swordsman', category: '絕技', type: 'physical', targetType: 'all', maxLevel: 3, levelReq: 25, prerequisite: { skillId: 'whirlwind', level: 3 }, 
        levels: [
            { mpCost: 50, damageMultiplier: 2.0, description: '[絕技] 對所有敵人造成<span class="text-yellow-400">200%</span>物理傷害。' },
            { mpCost: 55, damageMultiplier: 2.3, description: '[絕技] 對所有敵人造成<span class="text-yellow-400">230%</span>物理傷害。' },
            { mpCost: 60, damageMultiplier: 3.3, effect: { id: 'bladeStorm-debuff', name: '風暴撕裂', type: 'debuff', stats: { atk: -20, spi: -20, def: -20 }, turns: 2 }, description: '[絕技] 造成<span class="text-yellow-400">330%</span>物理傷害，並<span class="text-orange-400">大幅削弱</span>所有敵人。' }
    ]},
    
    // --- 修士 (Monk) ---
    spiritualPalm: { name: '靈氣掌', class:'monk', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 3, levelReq: 1, 
        levels: [
            { mpCost: 8, damageMultiplier: 1.5, description: '[單體] 造成<span class="text-purple-400">150%</span>靈力傷害。' },
            { mpCost: 9, damageMultiplier: 1.6, description: '[單體] 造成<span class="text-purple-400">160%</span>靈力傷害。' },
            { mpCost: 10, damageMultiplier: 1.7, special: { type: 'drain_mp', value: 20 }, description: '[單體] 造成<span class="text-purple-400">170%</span>靈力傷害，並吸收<span class="text-blue-400">20</span>點法力。' },
    ]},
    chiWave: { name: '真氣波', class:'monk', category: '攻擊', type: 'magical', targetType: 'all', maxLevel: 3, levelReq: 3, prerequisite: { skillId: 'spiritualPalm', level: 2 },
        levels: [
            { mpCost: 20, damageMultiplier: 1.2, description: '[範圍] 對所有敵人造成<span class="text-purple-400">120%</span>靈力傷害。' },
            { mpCost: 22, damageMultiplier: 1.3, description: '[範圍] 對所有敵人造成<span class="text-purple-400">130%</span>靈力傷害。' },
            { mpCost: 24, damageMultiplier: 1.4, special: { type: 'percent_hp_damage', value: 0.05 }, description: '[範圍] 造成<span class="text-purple-400">140%</span>靈力傷害，並附加敵人<span class="text-red-400">5%</span>最大生命的傷害。' },
    ]},
    lifeBalance: { name: '生死平衡', class:'monk', category: '治療', type: 'heal_attack', targetType: 'self', maxLevel: 3, levelReq: 5, prerequisite: { skillId: 'chiWave', level: 1 }, 
        levels: [
            { mpCost: 18, healRatio: 0.5, attackRatio: 0.7, description: '[治療/範圍] 治療自身<span class="text-green-400">50%靈力</span>生命，並對敵造成<span class="text-purple-400">70%治療量</span>傷害。' },
            { mpCost: 20, healRatio: 0.6, attackRatio: 0.8, description: '[治療/範圍] 治療自身<span class="text-green-400">60%靈力</span>生命，並對敵造成<span class="text-purple-400">80%治療量</span>傷害。' },
            { mpCost: 22, healRatio: 0.7, attackRatio: 0.9, description: '[治療/範圍] 治療自身<span class="text-green-400">70%靈力</span>生命，並對敵造成<span class="text-purple-400">90%治療量</span>傷害。' },
    ]},
    serenity: { name: '心如止水', class:'monk', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 8,
        levels: [
            { mpCost: 22, effect: { id: 'serenity', name: '心如止水', type: 'buff', stats: { spi: 15, hp: 50 }, turns: 3}, description: '[增益] 提升<span class="text-green-400">15</span>靈力與<span class="text-green-400">50</span>生命上限，持續3回合。' },
            { mpCost: 24, effect: { id: 'serenity', name: '心如止水', type: 'buff', stats: { spi: 20, hp: 65 }, turns: 3}, description: '[增益] 提升<span class="text-green-400">20</span>靈力與<span class="text-green-400">65</span>生命上限，持續3回合。' },
            { mpCost: 26, effect: { id: 'serenity', name: '心如止水', type: 'buff', stats: { spi: 25, hp: 70 }, turns: 3}, description: '[增益] 提升<span class="text-green-400">25</span>靈力與<span class="text-green-400">70</span>生命上限，持續3回合。' },
    ]},
    divineStrike: { name: '神聖打擊', class:'monk', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 3, levelReq: 10, prerequisite: { skillId: 'serenity', level: 1 },
        levels: [
            { mpCost: 25, damageMultiplier: 1.8, special: { type: 'bonus_vs_low_level', diff: 2, bonus: 1.25 }, description: '[單體] 造成<span class="text-purple-400">180%</span>靈力傷害，對低等級敵人更有效。' },
            { mpCost: 26, damageMultiplier: 1.9, special: { type: 'bonus_vs_low_level', diff: 2, bonus: 1.25 }, description: '[單體] 造成<span class="text-purple-400">190%</span>靈力傷害，對低等級敵人更有效。' },
            { mpCost: 27, damageMultiplier: 1.95, special: { type: 'bonus_vs_low_level', diff: 2, bonus: 1.25 }, description: '[單體] 造成<span class="text-purple-400">195%</span>靈力傷害，對低等級敵人更有效。' },
    ]},
    guardianSpirit: { name: '守護靈', class:'monk', category: '輔助', type: 'buff', targetType: 'self', maxLevel: 1, levelReq: 7, prerequisite: { skillId: 'lifeBalance', level: 3 },
        levels: [{ mpCost: 25, effect: {id: 'guardianSpirit', name: '守護靈', type: 'buff', turns: 3}, description: '[增益] 召喚守護靈，在你的回合開始時自動攻擊敵人，持續3回合。'}]},
    innerPeace: { name: '心靜如水', class:'monk', category: '輔助', type: 'utility', targetType: 'self', maxLevel: 1, levelReq: 13,
        levels: [{ mpCost: 20, special: { type: 'restore_mp_percent', value: 0.3 }, description: '[輔助] 平靜心靈，立即恢復<span class="text-blue-400">30%</span>最大法力值。'}]},
    karmaBlade: { name: '業報之刃', class:'monk', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 18,
        levels: [
            { mpCost: 28, special: { type: 'karma_buff', ratio: 0.5 }, effect: { id: 'karmaBlade', name: '業報', type: 'buff', stat: 'spi', value: 0, turns: 2 }, description: '[增益] 將<span class="text-red-400">50%已損失生命</span>轉化為靈力，持續2回合。'},
            { mpCost: 28, special: { type: 'karma_buff', ratio: 0.5 }, effect: { id: 'karmaBlade', name: '業報', type: 'buff', stat: 'spi', value: 0, turns: 3 }, description: '[增益] 將<span class="text-red-400">50%已損失生命</span>轉化為靈力，持續3回合。'},
            { mpCost: 28, special: { type: 'karma_buff', ratio: 0.5 }, effect: { id: 'karmaBlade', name: '業報', type: 'buff', stat: 'spi', value: 0, turns: 4 }, description: '[增益] 將<span class="text-red-400">50%已損失生命</span>轉化為靈力，持續4回合。'},
    ]},
    enlightenment: { name: '頓悟', class:'monk', category: '被動', type: 'passive', maxLevel: 1, levelReq: 28, 
        levels: [{ description: '[被動] 戰鬥中每次有單位行動後，都有<span class="text-yellow-400">20%</span>機率恢復<span class="text-green-400">15%</span>生命與<span class="text-blue-400">20%</span>法力。'}]
    },
    thousandPalms: { name: '千手神通', class:'monk', category: '絕技', type: 'magical', targetType: 'random', maxLevel: 3, levelReq: 22, prerequisite: { skillId: 'karmaBlade', level: 1 }, 
        levels: [
            { mpCost: 40, damageMultiplier: 0.8, hits: 5, description: '[絕技] <span class="text-yellow-400">隨機攻擊5次</span>，每次造成80%靈力傷害。' },
            { mpCost: 45, damageMultiplier: 0.9, hits: 5, description: '[絕技] <span class="text-yellow-400">隨機攻擊5次</span>，每次造成90%靈力傷害。' },
            { mpCost: 50, damageMultiplier: 1.0, hits: 5, description: '[絕技] <span class="text-yellow-400">隨機攻擊5次</span>，每次造成100%靈力傷害。' }
    ]},

    // --- 獸人 (Orc) ---
    savageCleave: { name: '野蠻劈砍', class:'orc', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 1, 
        levels: [
            { mpCost: 6, damageMultiplier: 1.6, description: '[單體] 造成<span class="text-yellow-400">160%</span>攻擊力的傷害。' },
            { mpCost: 7, damageMultiplier: 1.8, description: '[單體] 造成<span class="text-yellow-400">180%</span>攻擊力的傷害。' },
            { mpCost: 8, damageMultiplier: 2.2, description: '[單體] 造成<span class="text-yellow-400">220%</span>攻擊力的傷害。' },
    ]},
    earthStomp: { name: '大地踐踏', class:'orc', category: '攻擊', type: 'physical', targetType: 'all', maxLevel: 3, levelReq: 3, prerequisite: { skillId: 'savageCleave', level: 2 }, 
        levels: [
            { mpCost: 18, damageMultiplier: 1.2, description: '[範圍] 造成<span class="text-yellow-400">120%</span>攻擊力的傷害。' },
            { mpCost: 20, damageMultiplier: 1.45, description: '[範圍] 造成<span class="text-yellow-400">145%</span>攻擊力的傷害。' },
            { mpCost: 22, damageMultiplier: 1.6, description: '[範圍] 造成<span class="text-yellow-400">160%</span>攻擊力的傷害。' },
    ]},
    frenzy: { name: '狂暴', class:'orc', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 5, prerequisite: { skillId: 'savageCleave', level: 1 }, 
        levels: [
            { hpCost: 0.1, effect: {id: 'frenzy', name: '狂暴', type: 'buff', stat: 'atk', value: 20, turns: 3}, description: '[增益] 犧牲<span class="text-red-400">10%</span>生命，換取<span class="text-green-400">20</span>點攻擊力，持續3回合。' },
            { hpCost: 0.1, effect: {id: 'frenzy', name: '狂暴', type: 'buff', stat: 'atk', value: 25, turns: 3}, description: '[增益] 犧牲<span class="text-red-400">10%</span>生命，換取<span class="text-green-400">25</span>點攻擊力，持續3回合。' },
            { hpCost: 0.1, effect: {id: 'frenzy', name: '狂暴', type: 'buff', stat: 'atk', value: 30, turns: 3}, description: '[增益] 犧牲<span class="text-red-400">10%</span>生命，換取<span class="text-green-400">30</span>點攻擊力，持續3回合。' },
    ]},
    brutalCharge: { name: '殘暴衝鋒', class:'orc', category: '控制', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 8, prerequisite: { skillId: 'frenzy', level: 1 }, 
        levels: [
            { mpCost: 20, damageMultiplier: 1.8, effect: {id: 'stun', name: '昏迷', type: 'stun', turns: 1}, description: '[單體] 造成<span class="text-yellow-400">180%</span>傷害並<span class="text-orange-400">擊暈</span>敵人一回合。' },
            { mpCost: 21, damageMultiplier: 1.9, effect: {id: 'stun', name: '昏迷', type: 'stun', turns: 1}, description: '[單體] 造成<span class="text-yellow-400">190%</span>傷害並<span class="text-orange-400">擊暈</span>敵人一回合。' },
            { mpCost: 22, damageMultiplier: 2.0, effect: {id: 'stun', name: '昏迷', type: 'stun', turns: 1}, description: '[單體] 造成<span class="text-yellow-400">200%</span>傷害並<span class="text-orange-400">擊暈</span>敵人一回合。' },
    ]},
    bloodlust: { name: '嗜血', class:'orc', category: '被動', type: 'passive', maxLevel: 1, levelReq: 10,
        levels: [{ description: '[被動] 你的所有攻擊都會吸取造成傷害<span class="text-green-400">10%</span>的生命值。'}]},
    demoralizingShout: { name: '挑撥', class:'orc', category: '減益', type: 'debuff', targetType: 'single', maxLevel: 3, levelReq: 4, prerequisite: { skillId: 'savageCleave', level: 2 },
        levels: [
            { mpCost: 10, effect: {id: 'demoralized', name: '弱化', type: 'debuff', stat: 'def', value: -15, turns: 3}, description: '[減益] <span class="text-orange-400">弱化</span>敵人，使其防禦降低15點，持續3回合。' },
            { mpCost: 12, effect: {id: 'demoralized', name: '弱化', type: 'debuff', stat: 'def', value: -20, turns: 3}, description: '[減益] <span class="text-orange-400">弱化</span>敵人，使其防禦降低20點，持續3回合。' },
            { mpCost: 14, effect: {id: 'demoralized', name: '弱化', type: 'debuff', stat: 'def', value: -25, turns: 3}, description: '[減益] <span class="text-orange-400">弱化</span>敵人，使其防禦降低25點，持續3回合。' },
    ]},
    stoneSkin: { name: '石膚', class:'orc', category: '增益', type: 'buff', targetType: 'self', maxLevel: 3, levelReq: 7, 
        levels: [
            { mpCost: 12, effect: {id: 'stoneSkinOrc', name: '石膚', type: 'buff', stat: 'def', value: 25, turns: 3}, description: '[增益] 提升<span class="text-green-400">25</span>點防禦，持續3回合。' },
            { mpCost: 14, effect: {id: 'stoneSkinOrc', name: '石膚', type: 'buff', stat: 'def', value: 30, turns: 3}, description: '[增益] 提升<span class="text-green-400">30</span>點防禦，持續3回合。' },
            { mpCost: 16, effect: {id: 'stoneSkinOrc', name: '石膚', type: 'buff', stat: 'def', value: 36, turns: 3}, description: '[增益] 提升<span class="text-green-400">36</span>點防禦，持續3回合。' },
    ]},
    unbreakable: { name: '不倒', class:'orc', category: '輔助', type: 'utility', targetType: 'self', maxLevel: 1, levelReq: 19,
        levels: [{ mpCost: 30, special: { type: 'unbreakable' }, effect: {id: 'unbreakable', name: '不倒', type: 'buff', turns: 2}, description: '[輔助] 將生命降至<span class="text-red-400">20%</span>，2回合內<span class="text-green-400">免疫所有傷害</span>。'}]},
    rampage: { name: '暴走', class:'orc', category: '被動', type: 'passive', maxLevel: 1, levelReq: 26, 
        levels: [{ description: '[被動] 擊敗敵人時會進入<span class="text-red-500">暴走</span>狀態，攻擊力提升1倍，但每次攻擊會自行扣最大生命5%，持續2回合。'}]},
    overwhelm: { name: '壓制', class:'orc', category: '絕技', type: 'physical', targetType: 'single', maxLevel: 3, levelReq: 14, prerequisite: { skillId: 'bloodlust', level: 1 }, 
        levels: [
            { mpCost: 25, special: { type: 'overwhelm', threshold: 0.5, multiplier: 2.5, base: 1.9 }, description: '[絕技] 對生命低於50%的敵人造成<span class="text-yellow-400">250%</span>傷害，否則為190%。' },
            { mpCost: 28, special: { type: 'overwhelm', threshold: 0.55, multiplier: 2.8, base: 2.0 }, description: '[絕技] 對生命低於55%的敵人造成<span class="text-yellow-400">280%</span>傷害，否則為200%。' },
            { mpCost: 32, special: { type: 'overwhelm', threshold: 0.65, multiplier: 3.55, base: 2.1 }, description: '[絕技] 對生命低於65%的敵人造成<span class="text-yellow-400">355%</span>傷害，否則為210%。' },
    ]},

    // --- 死靈 (Necromancer) ---
    boneSpear: { name: '骸骨之矛', class:'necromancer', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 3, levelReq: 1,
        levels: [
            { mpCost: 10, damageMultiplier: 1.8, description: '[單體] 造成<span class="text-purple-400">180%</span>靈力傷害。' },
            { mpCost: 11, damageMultiplier: 1.9, description: '[單體] 造成<span class="text-purple-400">190%</span>靈力傷害。' },
            { mpCost: 12, damageMultiplier: 2.0, description: '[單體] 造成<span class="text-purple-400">200%</span>靈力傷害。' },
    ]},
    boneNova: { name: '骸骨新星', class:'necromancer', category: '攻擊', type: 'magical', targetType: 'all', maxLevel: 3, levelReq: 3, prerequisite: { skillId: 'boneSpear', level: 2 },
        levels: [
            { mpCost: 25, damageMultiplier: 1.3, description: '[範圍] 對所有敵人造成<span class="text-purple-400">130%</span>靈力傷害。' },
            { mpCost: 28, damageMultiplier: 1.5, description: '[範圍] 對所有敵人造成<span class="text-purple-400">150%</span>靈力傷害。' },
            { mpCost: 32, damageMultiplier: 1.6, special: { type: 'lifesteal_on_damage', ratio: 0.25 }, description: '[範圍] 造成<span class="text-purple-400">160%</span>靈力傷害，並吸取<span class="text-green-400">25%</span>總傷害的生命。' },
    ]},
    lifeDrain: { name: '生命汲取', class:'necromancer', category: '攻擊', type: 'magical_drain', targetType: 'single', maxLevel: 1, levelReq: 5, prerequisite: { skillId: 'boneSpear', level: 1 }, 
        levels: [
            { mpCost: 18, damageMultiplier: 1.5, drainRatio: 0.5, description: '[單體] 吸取敵人生命，造成<span class="text-purple-400">150%</span>靈力傷害並恢復<span class="text-green-400">50%</span>傷害的生命。' },
    ]},
    curse: { name: '詛咒', class:'necromancer', category: '減益', type: 'debuff', targetType: 'all', maxLevel: 3, levelReq: 8,
        levels: [
            { mpCost: 15, effect: {id: 'curse', name: '詛咒', type: 'debuff', stat: 'def', value: -10, turns: 3}, description: '[範圍減益] <span class="text-orange-400">削弱</span>所有敵人10點防禦，持續3回合。' },
            { mpCost: 18, effect: {id: 'curse', name: '詛咒', type: 'debuff', stat: 'def', value: -20, turns: 3}, description: '[範圍減益] <span class="text-orange-400">削弱</span>所有敵人20點防禦，持續3回合。' },
            { mpCost: 21, effect: {id: 'curse', name: '詛咒', type: 'debuff', stat: 'def', value: -25, turns: 3}, description: '[範圍減益] <span class="text-orange-400">削弱</span>所有敵人25點防禦，持續3回合。' },
    ]},
    shadowStep: { name: '暗影步伐', class:'necromancer', category: '增益', type: 'utility', targetType: 'self', maxLevel: 1, levelReq: 10, prerequisite: { skillId: 'curse', level: 1 },
        levels: [{ mpCost: 20, special: { type: 'next_skill_boost', critRate: 3, critDamage: 2 }, description: '[增益] 下一次技能攻擊必定暴擊，且暴擊傷害提升<span class="text-red-500">200%</span>。'}]},
    hellsReaper: { name: '地獄收割', class:'necromancer', category: '攻擊', type: 'utility', targetType: 'single', maxLevel: 3, levelReq: 4,
        levels: [
            { mpCost: 20, special: { type: 'reap', levelDiff: 3, chance: 0.75 }, description: '[單體] 對等級低於你3級的敵人，有<span class="text-yellow-400">75%</span>機率使其生命歸<span class="text-red-500">1</span>。'},
            { mpCost: 20, special: { type: 'reap', levelDiff: 2, chance: 0.75 }, description: '[單體] 對等級低於你2級的敵人，有<span class="text-yellow-400">75%</span>機率使其生命歸<span class="text-red-500">1</span>。'},
            { mpCost: 20, special: { type: 'reap', levelDiff: 1, chance: 0.75 }, description: '[單體] 對等級低於你1級的敵人，有<span class="text-yellow-400">75%</span>機率使其生命歸<span class="text-red-500">1</span>。'},
    ]},
    corpseExplosion: { name: '屍爆', class:'necromancer', category: '被動', type: 'passive', maxLevel: 3, levelReq: 11, prerequisite: { skillId: 'boneNova', level: 2 }, 
        levels: [
            { description: '[被動] 每當有敵人死亡，回復<span class="text-green-400">10</span>點靈力。'},
            { description: '[被動] 每當有敵人死亡，回復<span class="text-green-400">20</span>點靈力。'},
            { description: '[被動] 每當有敵人死亡，回復<span class="text-green-400">30</span>點靈力。'},
    ]},
    soulSiphon: { name: '靈魂虹吸', class:'necromancer', category: '輔助', type: 'utility', targetType: 'single', maxLevel: 3, levelReq: 16,
        levels: [
            { mpCost: 15, special: { type: 'drain_mp_percent', value: 0.6 }, description: '[單體] <span class="text-blue-400">吸取</span>敵人<span class="text-blue-400">60%</span>當前法力。'},
            { mpCost: 15, special: { type: 'drain_mp_percent', value: 0.7 }, description: '[單體] <span class="text-blue-400">吸取</span>敵人<span class="text-blue-400">70%</span>當前法力。'},
            { mpCost: 15, special: { type: 'drain_mp_percent', value: 0.8 }, description: '[單體] <span class="text-blue-400">吸取</span>敵人<span class="text-blue-400">80%</span>當前法力。'},
    ]},
    trueKingship: { name: '真命王者', class:'necromancer', category: '絕技', type: 'utility', targetType: 'self', maxLevel: 1, levelReq: 21,
        levels: [{ mpCost: 50, special: { type: 'true_kingship'}, description: '[絕技] 啟用後，下一個死亡的敵人將會爆炸，對其他敵人造成其<span class="text-red-400">50%</span>最大生命的傷害並<span class="text-orange-400">昏迷</span>。(每場戰鬥一次)'}] },
    deathPact: { name: '死亡契約', class:'necromancer', category: '被動', type: 'passive', maxLevel: 1, levelReq: 27,
        levels: [{ description: '[被動] 死亡時，原地滿血法復活，並提升<span class="text-green-400">15</span>靈力與<span class="text-green-400">5</span>速度(每場戰鬥一次)，再次死亡將損失<span class="text-red-500">所有</span>金錢。'}]},

    // 新增強力技能書專用技能（獨立於職業技能，更強力）
    superWhirlwind: { name: '超級旋風斬', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'all', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 2.0, description: '[範圍] 對所有敵人造成<span class="text-yellow-400">200%</span>攻擊力的物理傷害（比旋風斬強60%）。' }]
    },
    superLifeBalance: { name: '超級生死平衡', class:'monk', category: '治療', type: 'heal_attack', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 30, healRatio: 1.0, attackRatio: 1.2, description: '[治療/範圍] 治療自身<span class="text-green-400">100%靈力</span>生命，並對敵造成<span class="text-purple-400">120%治療量</span>傷害（比生死平衡強40%）。' }]
    },
    superFrenzy: { name: '超級狂暴', class:'orc', category: '增益', type: 'buff', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ hpCost: 0.05, effect: {id: 'superFrenzy', name: '超級狂暴', type: 'buff', stat: 'atk', value: 40, turns: 3}, description: '[增益] 犧牲<span class="text-red-400">5%</span>生命，換取<span class="text-green-400">40</span>點攻擊力，持續3回合（比狂暴強33%）。' }]
    },
    superLifeDrain: { name: '超級生命汲取', class:'necromancer', category: '攻擊', type: 'magical_drain', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 2.0, drainRatio: 0.75, description: '[單體] 吸取敵人生命，造成<span class="text-purple-400">200%</span>靈力傷害並恢復<span class="text-green-400">75%</span>傷害的生命（比生命汲取強50%）。' }]
    },

    // 敵人技能 (不需升級，固定Lv1)
    goblinRush: { name: '哥布林衝鋒', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.2, description: '[單體] 造成120%物理傷害。' }] },
    poisonBite: { name: '毒咬', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.1, effect: {id: 'poison', name: '中毒', type: 'dot', value: 0.05, turns: 3}, description: '[單體] 造成110%物理傷害，並造成中毒，持續3回合每回合損失5%最大生命。' }] },
    tuskGore: { name: '尖牙貫穿', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.3, description: '[單體] 造成130%物理傷害。' }] },
    furiousBite: { name: '狂怒撕咬', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.4, description: '[單體] 造成140%物理傷害。' }] },
    hobgoblinSmash: { name: '重擊', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.5, description: '[單體] 造成150%物理傷害。' }] },
    shamanCurse: { name: '薩滿詛咒', class:'enemy', category: '減益', type: 'debuff', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 10, effect: {id: 'curse', name: '詛咒', type: 'debuff', stat: 'atk', value: -10, turns: 3}, description: '[減益] 削弱目標攻擊力10點，持續3回合。' }] },
    minorHeal: { name: '小癒', class:'enemy', category: '治療', type: 'heal', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 15, healAmount: 50, description: '[治療] 恢復50點生命。' }] },
    shadowBlast: { name: '暗影衝擊', class:'enemy', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 15, damageMultiplier: 1.3, description: '[單體] 造成130%靈力傷害。' }] },
    earthSlam: { name: '大地猛擊', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.6, description: '[單體] 造成160%物理傷害。' }] },
    battleCry: { name: '戰吼', class:'enemy', category: '增益', type: 'buff', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 10, effect: {id: 'battleCry', name: '戰吼', type: 'buff', stat: 'atk', value: 10, turns: 3}, description: '[增益] 提升10點攻擊力，持續3回合。' }] },
    poisonSting: { name: '毒刺', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.2, effect: {id: 'poison', name: '中毒', type: 'dot', value: 0.1, turns: 2}, description: '[單體] 造成120%物理傷害，並造成中毒，持續2回合每回合損失10%最大生命。' }] },
    wingSlash: { name: '翼斬', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.5, description: '[單體] 造成150%物理傷害。' }] },
    trollRegen: { name: '巨魔再生', class:'enemy', category: '治療', type: 'heal', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, special: { type: 'regen', ratio: 0.15 }, description: '[治療] 每回合恢復15%生命。' }] },
    summonSkeleton: { name: '召喚骷髏', class:'enemy', category: '召喚', type: 'summon', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 20, special: { type: 'summon', monster: 'skeleton' }, description: '[召喚] 召喚一個骷髏兵助戰。' }] },
    charge: { name: '衝鋒', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.8, description: '[單體] 造成180%物理傷害。' }] },
    petrifyingGaze: { name: '石化凝視', class:'enemy', category: '減益', type: 'debuff', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 15, effect: {id: 'petrified', name: '石化', type: 'debuff', stat: 'speed', value: -10, turns: 2}, description: '[減益] 降低目標10點速度，持續2回合。' }] },
    fireBreath: { name: '火焰吐息', class:'enemy', category: '攻擊', type: 'magical', targetType: 'all', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 30, damageMultiplier: 1.5, description: '[範圍] 對所有敵人造成150%靈力傷害。' }] },
    multiBite: { name: '多重咬擊', class:'enemy', category: '攻擊', type: 'physical', targetType: 'random', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.0, hits: 3, description: '[隨機] 隨機攻擊3次，每次造成100%物理傷害。' }] },
    elementalBlast: { name: '元素衝擊', class:'enemy', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 1.8, description: '[單體] 造成180%靈力傷害。' }] },
    paralyzingTouch: { name: '麻痺之觸', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.2, effect: {id: 'paralyzed', name: '麻痺', type: 'debuff', stat: 'eva', value: -20, turns: 2}, description: '[單體] 造成120%物理傷害，並降低目標20點閃避，持續2回合。' }] },
    minorFireball: { name: '小火球', class:'enemy', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 10, damageMultiplier: 1.3, description: '[單體] 造成130%靈力傷害。' }] },
    ogreClub: { name: '食人魔棍擊', class:'enemy', category: '攻擊', type: 'physical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 0, damageMultiplier: 1.6, description: '[單體] 造成160%物理傷害。' }] },
    waterJet: { name: '水箭', class:'enemy', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 20, damageMultiplier: 1.5, description: '[單體] 造成150%靈力傷害。' }] },
    majorHeal: { name: '大癒', class:'enemy', category: '治療', type: 'heal', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 30, healAmount: 200, description: '[治療] 恢復200點生命。' }] },
    whirlwind: { name: '旋風', class:'enemy', category: '攻擊', type: 'physical', targetType: 'all', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 1.2, description: '[範圍] 對所有敵人造成120%物理傷害。' }] },
    divineStrike: { name: '神聖打擊', class:'enemy', category: '攻擊', type: 'magical', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 30, damageMultiplier: 2.0, description: '[單體] 造成200%靈力傷害。' }] },

    // 新增強力技能書專用技能（獨立於職業技能，更強力）
    superWhirlwind: { name: '超級旋風斬', class:'swordsman', category: '攻擊', type: 'physical', targetType: 'all', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 2.0, description: '[範圍] 對所有敵人造成<span class="text-yellow-400">200%</span>攻擊力的物理傷害（比旋風斬強60%）。' }]
    },
    superLifeBalance: { name: '超級生死平衡', class:'monk', category: '治療', type: 'heal_attack', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 30, healRatio: 1.0, attackRatio: 1.2, description: '[治療/範圍] 治療自身<span class="text-green-400">100%靈力</span>生命，並對敵造成<span class="text-purple-400">120%治療量</span>傷害（比生死平衡強40%）。' }]
    },
    superFrenzy: { name: '超級狂暴', class:'orc', category: '增益', type: 'buff', targetType: 'self', maxLevel: 1, levelReq: 0, 
        levels: [{ hpCost: 0.05, effect: {id: 'superFrenzy', name: '超級狂暴', type: 'buff', stat: 'atk', value: 40, turns: 3}, description: '[增益] 犧牲<span class="text-red-400">5%</span>生命，換取<span class="text-green-400">40</span>點攻擊力，持續3回合（比狂暴強33%）。' }]
    },
    superLifeDrain: { name: '超級生命汲取', class:'necromancer', category: '攻擊', type: 'magical_drain', targetType: 'single', maxLevel: 1, levelReq: 0, 
        levels: [{ mpCost: 25, damageMultiplier: 2.0, drainRatio: 0.75, description: '[單體] 吸取敵人生命，造成<span class="text-purple-400">200%</span>靈力傷害並恢復<span class="text-green-400">75%</span>傷害的生命（比生命汲取強50%）。' }]
    },
};